baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-learn"
languageCode = "en-us"
title = "Presentación Isa"
theme = "hugo-theme-learn"
[outputs]
home = [ "HTML", "RSS", "JSON"]
